{
  imports = [
    ./nheko.nix
    ./alacritty.nix
    ./firefox.nix
    ./flameshot.nix
    ./fonts.nix
    ./gtk.nix
    ./keepassxc.nix
    ./mpv.nix
    ./qt.nix
    ./gtk.nix
    ./vscode
    ./pavucontrol.nix
    ./gammastep.nix
    ./syncthing.nix
    ./backlight.nix
    ./autofirma.nix
  ];
}
