set nocompatible
filetype off
set autoindent

au BufRead /tmp/mutt* set tw=72|start

let g:zenburn_high_Contrast=1
colorscheme zenburn

set rtp+=~/.vim/bundle/vundle/ 
call vundle#rc()

Bundle 'gmarik/vundle'

filetype plugin indent on
