#! /bin/sh

bspc monitor -d 1 2 3 4

bspc config border_width          2
bspc config window_gap            6
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config history_aware_focus   true
bspc config apply_floating_atom   true
bspc config top_padding           18

bspc config focused_border_color '#6fc2ef'
bspc config urgent_border_color  '#fb9fb1'
bspc config normal_border_color  false

bspc rule -a Gimp desktop=^4 follow=on floating=on
bspc rule -a mpv floating=on
bspc rule -a Firefox desktop=^3

bspc desktop -l 1.monocle
bspc desktop -l 3.monocle
